spring:
  application:
    name: aestheticClinic
  main:
    allow-bean-definition-overriding: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3310/aesthetic
    username: enos
    password: 


  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhot:8080
server:
  port: 8080

